### ISSUE TITLE
ubuntu 14.04 source install  exec './scripts/initBasicExample.sh'  error

### ISSUE THREAD

**Issue by Anteoy** [lynckia/licode#1081]
**Environment**
os: ubuntu 14.04 server
install licode: from source
source git commit: e6cd88b32e008ec1342cfd6024b83a506a2caebe
**Description**
I follow the guid 'http://licode.readthedocs.io/en/master/from_source/',In strict accordance with the requirements of ubuntu14.04 and build step by step，when I exec 
```
./scripts/initBasicExample.sh
```
my server resp:
```
Error: Cannot find module 'errorhandler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/licode/extras/basic_example/basicServer.js:5:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
then I exec the cmd at initBasicExample.sh,the cmd :
```
node basicServer.js &
```
It can't work
any ideas?

**Comment by iamnibin** [comment]
Try npm install errorhandler   this will help,
Install "morgan" also.

**Comment by arsenicraghav** [comment]
Did you run the ./installBasicExample.sh ? 

What you are receiving is an error related to node_modules dependencies. You can either install these dependencies by hand by giving `npm install node_module_name` or simply run install ./installBasicExample.sh

Inside installBasicExample.sh we have:

`npm install --loglevel error express body-parser morgan errorhandler
`
