### ISSUE TITLE
lib not found: NICE-NOTFOUND check README on Ubuntu14.04 LTS

### ISSUE THREAD

**Issue by TTTTTTTK** [lynckia/licode#1140]
Installing erizo...
generating release
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so;/usr/lib/x86_64-linux-gnu/libgobject-2.0.so;/usr/lib/x86_64-linux-gnu/libgthread-2.0.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
--   regex
--   system
CMake Error at CMakeLists.txt:7 (message):
  lib not found: NICE-NOTFOUND check README
Call Stack (most recent call first):
  CMakeLists.txt:81 (test_lib)
What should i do to fix it ?

**Comment by TTTTTTTK** [comment]
I solve this problem by change my gcc & g++ version .
But i have another problem when excute this command：./initLicode.sh 
Error: Cannot find module './../../../licode_config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/licode/nuve/nuveAPI/mdb/dataBase.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Checking dir /root/licode/build/libdeps/nvm
Running nvm

**Comment by jcague** [comment]
not enough info provided
