### ISSUE TITLE
Error: Argument passed in must be a single String

### ISSUE THREAD

**Issue by neumerance** [lynckia/licode#1170]
Hi,

I'm following this instruction http://licode.readthedocs.io/en/stable/server_api/
I'm having an issue with server Server API.
For every command I use. it gives me this error.

`500 Error<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters<br> &nbsp; &nbsp;at new ObjectID (/opt/licode/node_modules/bson/lib/bson/objectid.js:50:11)<br> &nbsp; &nbsp;at Proxy.ObjectID (/opt/licode/node_modules/bson/lib/bson/objectid.js:31:42)<br> &nbsp; &nbsp;at Object.exports.getService (/opt/licode/nuve/nuveAPI/mdb/serviceRegistry.js:24:34)<br> &nbsp; &nbsp;at exports.authenticate (/opt/licode/nuve/nuveAPI/auth/nuveAuthenticator.js:67:25)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/licode/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/opt/licode/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/opt/licode/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/licode/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /opt/licode/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at param (/opt/licode/node_modules/express/lib/router/index.js:354:14)</pre>
</body>
</html>
`

**Comment by arsenicraghav** [comment]
please check if you have crypto library as part of your node module dependencies, there were some changes in the compilation of nuve.js which is used for dispatching server API calls.

**Comment by neumerance** [comment]
@arsenicraghav i did have crypto in my node modules but still, I still have the issue
