### ISSUE TITLE
Problem with log4js configuration when running initLicode.sh on OSX

### ISSUE THREAD

**Issue by harlanc** [lynckia/licode#1281]
When running the following script ,errors happen.I found serval similar errors in other licode issues and try the methods provided in the following answers,but it always fail.My platform is OSX10.13.6

MacBook-Pro ~/g/licode> ./scripts/initLicode.sh 
30528
30542
30796
Checking dir /Users/zexu/github/licode/build/libdeps/nvm
Running nvm
/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})` +
      ^

Error: Problem with log4js configuration: ({ appenders: 
   [ { type: 'console',
       layout: 
        { type: 'pattern',
          pattern: '%d  - %p: %c - %m',
          replaceConsole: true } } ],
  levels: 
   { AMQPER: 'ERROR',
     MAuthParser: 'ERROR',
     NuveAuthenticator: 'ERROR',
     CloudHandler: 'INFO',
     DataBase: 'ERROR',
     RoomRegistry: 'ERROR',
     ServiceRegistry: 'ERROR',
     TokenRegistry: 'ERROR',
     RoomResource: 'ERROR',
     RoomsResource: 'ERROR',
     ServiceResource: 'ERROR',
     ServicesResource: 'ERROR',
     TokenResource: 'ERROR',
     TokensResource: 'ERROR',
     Nuve: 'INFO',
     RPC: 'ERROR',
     RPCPublic: 'INFO' } }) - level "AMQPER" must be an object
    at tests.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (native)
    at Object.throwExceptionIf (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:23:9)
    at newLevels.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:115:21)
    at Array.forEach (native)
    at configuration.addListener (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:109:15)
    at listeners.forEach.listener (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:33)
    at Array.forEach (native)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:13)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/log4js.js:65:17)
Checking dir /Users/zexu/github/licode/build/libdeps/nvm
Running nvm
Found '/Users/zexu/github/licode/.nvmrc' with version <6.9.2>
Now using node v6.9.2 (npm v3.10.9)
Checking dir /Users/zexu/github/licode/build/libdeps/nvm
Running nvm
/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})` +
      ^

Error: Problem with log4js configuration: ({ appenders: 
   [ { type: 'console',
       layout: 
        { type: 'pattern',
          pattern: '%d  - %p: %c - %m',
          replaceConsole: true } } ],
  levels: 
   { AMQPER: 'ERROR',
     Client: 'INFO',
     Connection: 'INFO',
     ErizoController: 'INFO',
     ErizoJS: 'INFO',
     ErizoJSController: 'INFO',
     ErizoAgent: 'INFO',
     ErizoAgentReporter: 'ERROR',
     EcCloudHandler: 'INFO',
     Publisher: 'INFO',
     Subscriber: 'INFO',
     RoomController: 'INFO',
     RPCPublic: 'ERROR' } }) - level "AMQPER" must be an object
    at tests.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (native)
    at Object.throwExceptionIf (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:23:9)
    at newLevels.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:115:21)
    at Array.forEach (native)
    at configuration.addListener (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:109:15)
    at listeners.forEach.listener (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:33)
    at Array.forEach (native)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:13)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/log4js.js:65:17)
Found '/Users/zexu/github/licode/.nvmrc' with version <6.9.2>
Now using node v6.9.2 (npm v3.10.9)
[licode] Done, run ./scripts/initBasicExample.sh
zexu@zexudeMacBook-Pro ~/g/licode> /Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})` +
      ^

Error: Problem with log4js configuration: ({ appenders: 
   [ { type: 'console',
       layout: 
        { type: 'pattern',
          pattern: '%d  - %p: %c - %m',
          replaceConsole: true } } ],
  levels: 
   { AMQPER: 'ERROR',
     Client: 'INFO',
     Connection: 'INFO',
     ErizoController: 'INFO',
     ErizoJS: 'INFO',
     ErizoJSController: 'INFO',
     ErizoAgent: 'INFO',
     ErizoAgentReporter: 'ERROR',
     EcCloudHandler: 'INFO',
     Publisher: 'INFO',
     Subscriber: 'INFO',
     RoomController: 'INFO',
     RPCPublic: 'ERROR' } }) - level "AMQPER" must be an object
    at tests.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (native)
    at Object.throwExceptionIf (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:23:9)
    at newLevels.forEach (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:115:21)
    at Array.forEach (native)
    at configuration.addListener (/Users/zexu/github/licode/node_modules/log4js/lib/levels.js:109:15)
    at listeners.forEach.listener (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:33)
    at Array.forEach (native)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/configuration.js:36:13)
    at Object.configure (/Users/zexu/github/licode/node_modules/log4js/lib/log4js.js:65:17)

**Comment by kekkokk** [comment]
what version of log4js are you using?
please check in node_modules that you are using version 1.x.x, as with the new version they changed the model to define multiple loggers
