### ISSUE TITLE
.gulp is not a function

### ISSUE THREAD

**Issue by Javiiiie** [lynckia/licode#1396]
Hello, I'm having some problems to install licode on a new server with Ubuntu 14.04.

I'm installing one by one each error that "installErizo.sh -c" gives me, i'm stuck at this point:

`[erizo_controller] Installing node_modules for erizo_controller
Found '/home/veloria/licode/.nvmrc' with version <6.14.4>
Now using node v6.14.4 (npm v3.10.10)
licode@0.1.0 /home/veloria/licode
├── amqp@0.2.7
├── log4js@1.0.1
├── node-getopt@0.3.2
├── prom-client@11.2.1
├── sdp-transform@2.3.0
├── socket.io@2.0.3
└── uuid@3.1.0

[erizo_controller] Done, node_modules installed
/home/veloria/licode/erizo_controller/erizoClient/gulpfile.js:9
plugins.closureCompiler = require('google-closure-compiler-js').gulp();
                                                                ^

TypeError: require(...).gulp is not a function
    at Object.<anonymous> (/home/veloria/licode/erizo_controller/erizoClient/gulpfile.js:9:65)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at execute (/home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/index.js:196:24)
    at Liftoff.execute (/home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:201:12)
    at module.exports (/home/veloria/licode/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:191:5)
    at /home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:149:9
    at /home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/v8flags/index.js:135:14
    at /home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/v8flags/index.js:41:14
    at /home/veloria/licode/node_modules/gulp/node_modules/gulp-cli/node_modules/v8flags/index.js:53:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

I tried to install gulp global, locally but it doesn't work... could you help me?

**Comment by Javiiiie** [comment]
If I run it without "-c" i get this:

> [  6%] Completed 'project_nicer'
[  8%] Built target project_nicer
[ 45%] Built target webrtc
[ 81%] Built target erizo
Linking CXX executable tests
../erizo/liberizo.so: undefined reference to `boost::system::detail::system_category_ncx()'
../erizo/liberizo.so: undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
../erizo/liberizo.so: undefined reference to `boost::system::detail::generic_category_ncx()'

**Comment by lidedongsn** [comment]
try ubuntu16.04
