### ISSUE TITLE
Mongodb lib error

### ISSUE THREAD

**Issue by cracker0dks** [lynckia/licode#1414]
After some times of running without problems I get this error and licode crashs:

```
/opt/licode/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/opt/licode/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/opt/licode/node_modules/express/lib/response.js:170:12)
    at generateToken (/opt/licode/nuve/nuveAPI/resource/tokensResource.js:167:11)
    at tokenRegistry.addToken (/opt/licode/nuve/nuveAPI/resource/tokensResource.js:134:16)
    at db.tokens.save (/opt/licode/nuve/nuveAPI/mdb/tokenRegistry.js:61:12)
    at /opt/licode/node_modules/mongojs/lib/collection.js:118:7
    at /opt/licode/node_modules/mongojs/lib/collection.js:105:7
    at handleCallback (/opt/licode/node_modules/mongodb/lib/utils.js:120:56)
    at /opt/licode/node_modules/mongodb/lib/collection.js:1061:5
```

**Comment by cracker0dks** [comment]
not encountered this anymore, so closed for now
