### ISSUE TITLE
Fail to build docker image

### ISSUE THREAD

**Issue by vpoddubchak** [lynckia/licode#1503]
**Description**

I can't build docker image from latest sources of licode.

**Steps to reproduce the issue:**
1. `git clone https://github.com/lynckia/licode.git`
2. `cd licode`
3. `docker build -t licode-image .`

**Describe the results you received:**
Build failed with error:
```
8955 silly mapToRegistry uri https://registry.npmjs.org/find-up
8956 verbose request uri https://registry.npmjs.org/find-up
8957 verbose request no auth needed
8958 info attempt registry request try #1 at 1:39:55 PM
8959 http request GET https://registry.npmjs.org/find-up
8960 http 404 https://registry.npmjs.org/find-up
8961 verbose bad json <?xml version="1.0" encoding="UTF-8"?>
8961 verbose bad json <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>npm-registry-packages</BucketName><RequestId>DA6D73825C99A780</RequestId><HostId>z7VHfi/b4Qj0D9ss/s+2UFc3Hq4mVQsKGHaTI73kKZjtrL4TRKFbOhX3uqDMnJtKWvpEV3QIGUc=</HostId></Error>
8962 error registry error parsing json
8963 verbose headers { date: 'Tue, 19 Nov 2019 13:39:55 GMT',
8963 verbose headers   'content-type': 'application/xml',
8963 verbose headers   'transfer-encoding': 'chunked',
8963 verbose headers   connection: 'keep-alive',
8963 verbose headers   'set-cookie': [ '__cfduid=d3bab35f365f628eae3c750d8f1b98dcc1574170795; expires=Wed, 18-Nov-20 13:39:55 GMT; path=/; domain=.npmjs.org; HttpOnly' ],
8963 verbose headers   'cf-cache-status': 'HIT',
8963 verbose headers   'cache-control': 'max-age=300',
8963 verbose headers   'cf-ray': '538297ce1e44c40b-LED',
8963 verbose headers   age: '5',
8963 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
8963 verbose headers   vary: 'accept-encoding, accept',
8963 verbose headers   server: 'cloudflare',
8963 verbose headers   'content-encoding': 'gzip' }
8964 silly get cb [ 404,
8964 silly get   { date: 'Tue, 19 Nov 2019 13:39:55 GMT',
8964 silly get     'content-type': 'application/xml',
8964 silly get     'transfer-encoding': 'chunked',
8964 silly get     connection: 'keep-alive',
8964 silly get     'set-cookie': [ '__cfduid=d3bab35f365f628eae3c750d8f1b98dcc1574170795; expires=Wed, 18-Nov-20 13:39:55 GMT; path=/; domain=.npmjs.org; HttpOnly' ],
8964 silly get     'cf-cache-status': 'HIT',
8964 silly get     'cache-control': 'max-age=300',
8964 silly get     'cf-ray': '538297ce1e44c40b-LED',
8964 silly get     age: '5',
8964 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
8964 silly get     vary: 'accept-encoding, accept',
8964 silly get     server: 'cloudflare',
8964 silly get     'content-encoding': 'gzip' } ]
8965 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
8965 silly fetchPackageMetaData <?xml version="1.0" encoding="UTF-8"?>
8965 silly fetchPackageMetaData <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>npm-registry-packages</BucketName><RequestId>DA6D73825C99A780</RequestId><HostId>z7VHfi/b4Qj0D9ss/s+2UFc3Hq4mVQsKGHaTI73kKZjtrL4TRKFbOhX3uqDMnJtKWvpEV3QIGUc=</HostId></Error>
8965 silly fetchPackageMetaData     at Object.parse (native)
8965 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/opt/licode/build/libdeps/nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:23)
8965 silly fetchPackageMetaData     at /opt/licode/build/libdeps/nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:7
8965 silly fetchPackageMetaData     at Gunzip.onEnd (zlib.js:227:5)
8965 silly fetchPackageMetaData     at emitNone (events.js:91:20)
8965 silly fetchPackageMetaData     at Gunzip.emit (events.js:185:7)
8965 silly fetchPackageMetaData     at endReadableNT (_stream_readable.js:978:12)
8965 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
8965 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
8965 silly fetchPackageMetaData  error for find-up@^2.1.0 SyntaxError: Unexpected token < in JSON at position 0
8965 silly fetchPackageMetaData <?xml version="1.0" encoding="UTF-8"?>
8965 silly fetchPackageMetaData <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>npm-registry-packages</BucketName><RequestId>DA6D73825C99A780</RequestId><HostId>z7VHfi/b4Qj0D9ss/s+2UFc3Hq4mVQsKGHaTI73kKZjtrL4TRKFbOhX3uqDMnJtKWvpEV3QIGUc=</HostId></Error>
8965 silly fetchPackageMetaData     at Object.parse (native)
8965 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/opt/licode/build/libdeps/nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:23)
8965 silly fetchPackageMetaData     at /opt/licode/build/libdeps/nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:7
8965 silly fetchPackageMetaData     at Gunzip.onEnd (zlib.js:227:5)
8965 silly fetchPackageMetaData     at emitNone (events.js:91:20)
8965 silly fetchPackageMetaData     at Gunzip.emit (events.js:185:7)
8965 silly fetchPackageMetaData     at endReadableNT (_stream_readable.js:978:12)
8965 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
8965 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by vpoddubchak** [comment]
Fixed after update to #1500
