### ISSUE TITLE
initLicode.sh build script , Error: Cannot find module './../../erizoAPI/build/Release/addon'

### ISSUE THREAD

**Issue by Sleepingbug** [lynckia/licode#1520]
This problem has troubled me for a few days, I don't know how to solve it.

I compile the code according to the guidelines of this URL：
https://licode.readthedocs.io/en/master/from_source/
(same as http://lynckia.com/licode/install.html )

After some efforts, many problems were solved．
Operating environment：
Ubuntu 16.04 64-bit
node -v: v12.12.0
npm -v: 6.13.2
gcc version 5.5.0

Except when executing ./scripts/installErizo.sh
Except for the following error, nothing else is reported：
`
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! licode-erizo-api@0.1.0 preinstall: `./lint.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the licode-erizo-api@0.1.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

But proceed to ./scripts/initLicode.sh
It will report the same error continuously:
Error: Cannot find module './../../erizoAPI/build/Release/addon'

`root@78eaa057247b:/home/howard/licode-all/licode-master# ./scripts/initLicode.sh
13691
13796
13861
Checking dir /home/howard/licode-all/licode-master/build/libdeps/nvm
Running nvm
Checking dir /home/howard/licode-all/licode-master/build/libdeps/nvm
Running nvm
Found '/home/howard/licode-all/licode-master/.nvmrc' with version <12.13.0>
Now using node v12.13.0 (npm v6.12.0)
Checking dir /home/howard/licode-all/licode-master/build/libdeps/nvm
Running nvm
Found '/home/howard/licode-all/licode-master/.nvmrc' with version <12.13.0>
2019-12-07 06:49:10.093  - INFO: CloudHandler - New erizocontroller ( 5deb4b66a60c103905de04e4 ) in:  172.17.0.2
2019-12-07 06:49:10.097  - INFO: ErizoController - message: succesfully added to cloudHandler
Now using node v12.13.0 (npm v6.12.0)
[licode] Done, run ./scripts/initBasicExample.sh
root@78eaa057247b:/home/howard/licode-all/licode-master# 2019-12-07 06:49:10.469  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: d1bd7731-1649-fbab-d657-8a4dabbb05ee
[erizo-d1bd7731-1649-fbab-d657-8a4dabbb05ee] internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './../../erizoAPI/build/Release/addon'
Require stack:
- /home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js:90:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js'
  ]
}
2019-12-07 06:49:10.493  - INFO: ErizoAgent - message: closed, erizoId: d1bd7731-1649-fbab-d657-8a4dabbb05ee
2019-12-07 06:49:10.494  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 997c222b-7367-451c-6a85-af91eafe9195
[erizo-997c222b-7367-451c-6a85-af91eafe9195] internal/modules/cjs/loader.js:797
    throw err;
    ^
`

**Comment by Sleepingbug** [comment]
Failed to exec preinstall script

**Comment by Sleepingbug** [comment]
i've tried for a week but no results

**Comment by lodoyun** [comment]
Thanks for reporting this.
There is an issue with npm package dependencies. We added the `package-lock` files to version control in PR #1524 . You can try it directly in the branch, we will merge it soon

**Comment by Sleepingbug** [comment]
@lodoyun Thank you very much

**Comment by Sleepingbug** [comment]
I have downloaded the latest code to compile,
Although still not all went well , it turned out to compile.
@lodoyun  Thank you very much, your help is very important to me
