### ISSUE TITLE
Can not start Licode on Ubuntu 20.04

### ISSUE THREAD

**Issue by xSirrioNx** [lynckia/licode#1660]
Can not start on Ubuntu 20.04 (both WSL and server instance)
I use this manual: https://licode.readthedocs.io/en/master/from_source/

When i try to start Licode (`./scripts/initLicode.sh`), terminal starts to spam this error messages:
```
Error: libavresample.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/projects/licode/erizo_controller/erizoJS/erizoJS.js:88:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-11-23 16:35:11.836  - INFO: ErizoAgent - message: closed, erizoId: 62828f48-01cf-079d-ada7-760f856cf0db
2020-11-23 16:35:11.840  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 32f6faf1-79fb-f08b-9f91-b6177394ef8a
[erizo-32f6faf1-79fb-f08b-9f91-b6177394ef8a] internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
```

**Comment by jvdminne** [comment]
I ran into the same problem. I "fixed" it by issueing: 
ldconfig /path/to/your/licode/build/libdeps/build/lib

But I have to do this every time before starting Licode.
