### ISSUE TITLE
error occured when tried to compile and run basic example

### ISSUE THREAD

**Issue by xtycdd** [lynckia/licode#1722]
**Description**

I'm studying WebRTC and I learned about licode a few days ago. I hope to use licode to make a conference system. But I met difficulty in using licode.

**Steps to reproduce the issue:**
I used Ubuntu-18.04 and compiled as the following page says. 
https://licode.readthedocs.io/en/master/from_source/

I succeed to run installUbuntuDeps.sh installNuve.sh installErizo.sh installBasicExample.sh

when I tried to run installBasicExample.sh, something wrong occured like below.
Should I write a "licode_config" file first? Or how to get the file? I need help.

![image](https://user-images.githubusercontent.com/46333547/121674519-bf8d6100-cae4-11eb-96dc-eb3109475fb7.png)

**Comment by xtycdd** [comment]
when I copied licode_default.js in /licode/scripts to licode_config in /licode, it shows

root@LicodeTest:~/licode# ./scripts/initLicode.sh
9652
9661
Checking dir /root/licode/build/libdeps/nvm
Running nvm
/root/licode/nuve/nuveAPI/mdb/erizoControllerRegistry.js:11
  dataBase.db.collection('erizoControllers').find({}).toArray((err, erizoControllers) => {
              ^

TypeError: Cannot read property 'collection' of undefined
    at Object.exports.getErizoControllers (/root/licode/nuve/nuveAPI/mdb/erizoControllerRegistry.js:11:15)
    at Timeout.checkKA [as _onTimeout] (/root/licode/nuve/nuveAPI/cloudHandler.js:83:27)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Checking dir /root/licode/build/libdeps/nvm
Running nvm
Found '/root/licode/.nvmrc' with version <12.13.0>
Now using node v12.13.0 (npm v6.12.0)
Checking dir /root/licode/build/libdeps/nvm
Running nvm
Found '/root/licode/.nvmrc' with version <12.13.0>
Now using node v12.13.0 (npm v6.12.0)
[licode] Done, run ./scripts/initBasicExample.sh
root@LicodeTest:~/licode# 2021-06-15 01:59:17.331  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 7bf6509f-bf92-8542-bf27-9597337621ba
[erizo-7bf6509f-bf92-8542-bf27-9597337621ba] 2021-06-15 01:59:17.512  - INFO: ErizoJS - Starting ioThreadPool
[erizo-7bf6509f-bf92-8542-bf27-9597337621ba] 2021-06-15 01:59:17.545  - INFO: ErizoJS - message: Started, erizoId: 7bf6509f-bf92-8542-bf27-9597337621ba, isDebugMode: false
2021-06-15 01:59:21.880  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 5
2021-06-15 01:59:29.888  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 4
2021-06-15 01:59:37.891  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 3
2021-06-15 01:59:45.895  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 2
2021-06-15 01:59:53.899  - WARN: ErizoController - message: addECToCloudHandler cloudHandler does not respond, attemptsLeft: 1
2021-06-15 01:59:56.899  - ERROR: ErizoController - message: addECtoCloudHandler cloudHandler does not respond - fatal
