### ISSUE TITLE
TypeError: Cannot read property 'erizoControllerId' of null

### ISSUE THREAD

**Issue by goock** [lynckia/licode#813]
Hi,

This is related to commit: https://github.com/lynckia/licode/tree/2a5ea084b2a88de86351f94860b1736e58661792
Licode is installed on Ubuntu 14.04.

Nuve crash quite often with the following stack:
```
/opt/licode/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'erizoControllerId' of null
    at /opt/licode/nuve/nuveAPI/cloudHandler.js:259:18
    at /opt/licode/nuve/nuveAPI/mdb/roomRegistry.js:26:13
    at /opt/licode/node_modules/mongojs/lib/collection.js:50:5
    at handleCallback (/opt/licode/node_modules/mongodb/lib/utils.js:120:56)
    at /opt/licode/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/opt/licode/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/opt/licode/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /opt/licode/node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/opt/licode/node_modules/mongodb-core/lib/cursor.js:253:5)
    at /opt/licode/node_modules/mongodb-core/lib/connection/pool.js:461:18
```

I reviewed the code and likely this is related to the condition:
```
exports.deleteRoom = function (roomId, callback) {

    roomRegistry.getRoom(roomId, function (room) {
        if (!room.erizoControllerId) {
            callback('Success');
            return;
        }
        var rpcID = 'erizoController_' + room.erizoControllerId;
        rpc.callRpc(rpcID, 'deleteRoom', [roomId], {'callback': function (result) {
            callback(result);
        }});
    });
};
```

`room` variable seems to be null from `getRoom` function. Shouldn't it be checked additionally:
```
        if (room && !room.erizoControllerId) {
            callback('Success');
            return;
        }
```

Let me know if you need further information.

Thanks.

**Comment by aalonsog** [comment]
Thanks for the report! We will take a look and try to fix it ASAP
