### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by coolfat** [lynckia/licode#830]
HI, I am installing licode in Ubunut 14.04, the error happened.
I run the script, ./licode/scripts/initLicode.sh,  and the error message is blew:1187
1195
Checking dir /home/hfxing/WorkSpace/licode/build/libdeps/nvm
Running nvm
Checking dir /home/hfxing/WorkSpace/licode/build/libdeps/nvm
Running nvm
Found '/home/hfxing/WorkSpace/licode/.nvmrc' with version <6.9.2>
Now using node v6.9.2 (npm v3.10.9)
Checking dir /home/hfxing/WorkSpace/licode/build/libdeps/nvm
Running nvm
2017-03-30 15:16:38.906  - INFO: CloudHandler - New erizocontroller ( 58dcb0d6bb6caa6f6dacda36 ) in:  192.168.0.6
2017-03-30 15:16:38.915  - INFO: ErizoController - message: succesfully added to cloudHandler
Found '/home/hfxing/WorkSpace/licode/.nvmrc' with version <6.9.2>
Now using node v6.9.2 (npm v3.10.9)
[licode] Done, run ./scripts/initBasicExample.sh
2017-03-30 15:16:40.462  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: dbd3cf91-0cb1-50fa-071d-024fbb7f6378
[erizo-dbd3cf91-0cb1-50fa-071d-024fbb7f6378] module.js:471
    throw err;
    ^

_Error: Cannot find module './../../erizoAPI/build/Release/addon'_
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hfxing/WorkSpace/licode/erizo_controller/erizoJS/erizoJS.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

What's the problem? I lookfoward for you help.

**Comment by jcague** [comment]
seems like you had an issue when running installErizo.sh, please check the output of that script again to see if there's any problem.
