### ISSUE TITLE
eziroAgent: /licode/erizoAPI/build/Release/addon.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by TaGiang06011994** [lynckia/licode#920]
Error: /home/son/licode/erizoAPI/build/Release/addon.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/son/licode/erizo_controller/erizoJS/erizoJS.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Licode commit/release where the issue is happening**

**Additional environment details (Local, AWS, Docker, etc.):**

**Comment by TaGiang06011994** [comment]
I using node -v.0.10.37

**Comment by jcague** [comment]
Please, provide more info... Ubuntu version? did everything compile as expected?

**Comment by Sleepingbug** [comment]
i have a similar problem, how to fix it ?

`root@78eaa057247b:/home/howard/licode-all/licode-master# exit2019-12-06 06:06:03.922  - INFO: ErizoAgent - message: launched new ErizoJS, erizoId: 53bb30d8-89d4-036d-930c-f539672953c8
[erizo-53bb30d8-89d4-036d-930c-f539672953c8] internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module './../../erizoAPI/build/Release/addon'
Require stack:
- /home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js:90:11)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/howard/licode-all/licode-master/erizo_controller/erizoJS/erizoJS.js'
  ]
}
`
