### ISSUE TITLE
Error: Problem with log4js configuration: ({ appenders: .. Trying to start the Licode server.

### ISSUE THREAD

**Issue by arsenicraghav** [lynckia/licode#953]
I am executing the initLicode.sh script and it's throwing the following error: 

```
licode-server@abc-lt:~/licode/scripts$ sudo ./initLicode.sh 
1359
1394
Checking dir /home/licode-server/licode/build/libdeps/nvm
Running nvm
/home/licode-server/licode/node_modules/log4js/lib/configuration.js:37
        throw new Error(
        ^

Error: Problem with log4js configuration: ({ appenders: 
   [ { type: 'console',
       layout: 
        { type: 'pattern',
          pattern: '%d  - %p: %c - %m',
          replaceConsole: true } } ],
  levels: 
   { AMQPER: 'ERROR',
     MAuthParser: 'ERROR',
     NuveAuthenticator: 'ERROR',
     CloudHandler: 'INFO',
     DataBase: 'ERROR',
     RoomRegistry: 'ERROR',
     ServiceRegistry: 'ERROR',
     TokenRegistry: 'ERROR',
     RoomResource: 'ERROR',
     RoomsResource: 'ERROR',
     ServiceResource: 'ERROR',
     ServicesResource: 'ERROR',
     TokenResource: 'ERROR',
     TokensResource: 'ERROR',
     Nuve: 'INFO',
     RPC: 'ERROR',
     RPCPublic: 'INFO' } }) - must have a property "appenders" of type object.
    at tests.forEach (/home/licode-server/licode/node_modules/log4js/lib/configuration.js:37:15)
    at Array.forEach (native)
    at Configuration.throwExceptionIf (/home/licode-server/licode/node_modules/log4js/lib/configuration.js:35:11)
    at new Configuration (/home/licode-server/licode/node_modules/log4js/lib/configuration.js:190:10)
    at Object.configure (/home/licode-server/licode/node_modules/log4js/lib/log4js.js:172:12)
    at Object.<anonymous> (/home/licode-server/licode/nuve/nuveAPI/logger.js:19:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

```

**Comment by kekkokk** [comment]
same here with current master

**Comment by bigboyaaa** [comment]
same here with current master

**Comment by kekkokk** [comment]
you can make an hotfix:
in erizo_controller/installErizo_controller.sh
find log4js and replace with log4js@1.0.1

seems an incompatibility with the new log4js package

run ./installErizo_controller.sh after

**Comment by arsenicraghav** [comment]
Can anyone confirm if this PR [https://github.com/lynckia/licode/pull/956] addresses this issue ?

**Comment by jcague** [comment]
yes, it does, Travis is building the whole system again

**Comment by arsenicraghav** [comment]
I am closing it.
