### ISSUE TITLE
New version of Erizofc.js , throws an error on room.connect() 

### ISSUE THREAD

**Issue by yogeshgo05** [lynckia/licode#996]
Please advice , new version of erizofc.js is throwing the following error on room.connect . 

`var Erizo = require('.erizofc').Erizo; ` ,  I don't think  `.Erizo` scope is used any more in the latest 
Erizofc.js 

`/home/ubuntu/opt/mvp/lib/erizofc.js:2212
          const token = __WEBPACK_IMPORTED_MODULE_5__utils_Base64__["a" /* default */ ].decodeBase64(spec.token);
                                                                                                         ^

TypeError: Cannot read property 'token' of undefined
    at Object.Room.that.connect (/home/ubuntu/opt/mvp/lib/erizofc.js:2212:106)
    at Stream.init (/home/ubuntu/opt/mvp/lib/app/stream.js:33:14)
    at /home/ubuntu/opt/mvp/lib/app/licode.js:100:28
    at XMLHttpRequest.p.onreadystatechange (/home/ubuntu/opt/mvp/lib/nuve.js:30:250)
    at l (/home/ubuntu/opt/mvp/lib/nuve.js:6:506)
    at IncomingMessage.<anonymous> (/home/ubuntu/opt/mvp/lib/nuve.js:10:372)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE`

**Comment by yogeshgo05** [comment]
Please update your docs how to use Erizofc . Finally I found way to do that .  
`room = Erizo.Room(newIo, fakeConnection, {token: token});`

**Comment by lodoyun** [comment]
You don't really need to pass the `fakeConnection` that's only needed for Spine, should work automatically here.
Try it and if you still do not get the events I'd say it's a problem with your setup and we can discuss that in #994
